easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
        - App\Entity\Category
        - App\Entity\User
        - App\Entity\Profil
        - App\Entity\Comment
        - App\Entity\CommentLike
